### ISSUE TITLE
Images aren´t displayed correctly in IE 11

### ISSUE THREAD

**Issue by DTM-TYPO3** [sitegeist/sms-responsive-images#2]
Hello,

I´ve got an TYPO3 8.7.3 installation with your newest SMS extension. Images are shown correctly in Firefox and Chrome but Internet Explorer 11 is having a problem with the img-tag and doesn´t show the image at all. Maybe it´s because the src-attribute (as fallback) is missing?
Could you please fix that issue?

Thanks in advance,
Stefanie

**Comment by s2b** [comment]
Hello Stefanie,

you're correct that IE 11 doesn't show the images by default because they lack a src attribute. There are two possible ways you can fix that:

1. Recommended: Include [picturefill](http://scottjehl.github.io/picturefill/) into your website. This polyfill will implement the missing responsive images functionality in older browsers.
2. Tell the ViewHelper to render standard-compliant HTML markup instead of the markup suggested by picturefill. You can enable this by setting the [picturefill attribute of the ViewHelper](https://docs.typo3.org/typo3cms/extensions/sms_responsive_images/DeveloperManual/Index.html#picturefill) to false.

The reason why I implemented the ViewHelper this way is that standard compliant markup, while working better on older browsers, behaves worse on modern browsers. This would mean that modern browsers (which support responsive images on their own) would in some cases load images twice.

I hope this helps.

Simon
