### ISSUE TITLE
Partials override does not work

### ISSUE THREAD

**Issue by rowild** [sitegeist/sms-responsive-images#43]
I would like to use a different Partial template (in order to get rid of the width attribute, which I find superfluous) and use this typoscript:

```
lib.contentElement {
    // templateRootPaths.110 = EXT:theme/Resources/Private/Extensions/fluid_styled_content/Templates/
    partialRootPaths.110 = EXT:theme/Resources/Private/Extensions/fluid_styled_content/Partials/
    // layoutRootPaths.110 = EXT:theme/Resources/Private/Extensions/fluid_styled_content/Layouts/
}
```

The TypoScirpt browser does recognize the template path, where there is a Media/Rendering/Image.html file structure. However, sms-responsive-images is still rendering from its own file...

Am I doing something wrong here?

BTW: Typo3 8.7.22, sms-responsive-images 1.2

**Comment by rowild** [comment]
Sorry: the partial is recognized correctly. But the width attribute is still rendered. Why?
Also: the lowest breakpoint is 320 in my case, nevertheless the sizes attr and also the with attr (again) receive a 400, as can be seen in the devtools (400 is the original width of the image):
```html
<picture><source srcset="/fileadmin/_processed_/e/b/csm_anfahrtsplan_1f3fae8158.jpg 320w, /fileadmin/_processed_/e/b/csm_anfahrtsplan_a9168075c0.jpg 2400w" media="(min-width: 320px)" sizes="(min-width: 400px) 400px, 100vw"><img class="c-img ZZZ" srcset="/fileadmin/user_upload/landkarten/anfahrtsplan.jpg" width="400" alt=""></picture>
```

How can I get rid of the width attr? And get the proper numbers?

**Comment by rowild** [comment]
Any chance for some advice, please?

**Comment by s2b** [comment]
By default, the extension uses the `width` attribute to provide a reasonable fallback image. This is TYPO3's default behavior for content images and is configured via the TypoScript constant `styles.content.textmedia.maxW` (or `styles.content.textmedia.maxWInText` for text/image). It also uses that width to generate a default `sizes` query, as you can see in your example.

Currently, there is no way to remove the `width` attribute from the final `img` element, but this isn't possible with TYPO3's image viewhelper either. However, it shouldn't really matter because if you do responsive webdesign you override the image width by CSS anyways (e. g. `max-width: 100%; height: auto;`).

Concerning the `sizes` attribute, you can – and should – override it by specifying your query in TypoScript:

in constants:
```
tx_smsresponsiveimages.sizes = (min-width: 800px) 800px, 100vw
```

or setup:
```
lib.contentElement.settings.tx_smsresponsiveimages.sizes = (min-width: 800px) 800px, 100vw
```

An easy way to determine a good `sizes` query is to use [respimagelint](https://ausi.github.io/respimagelint/). You can also check the displayed image widths in each of your design breakpoints manually and create it based on those values.
